<?php

namespace zaboy\middleware\Middleware\Rest\Rql;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 21:20:24.
 */
class RqlParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var RqlParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RqlParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers zaboy\middleware\Middleware\Rest\Rql\RqlParser::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
